services:
  backend:
    build:
      context: ./backend
      network: host
      dockerfile: Dockerfile
    container_name: contracts-backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_ACCESS_SECRET=secret-access-token
      - JWT_REFRESH_SECRET=secret-refresh-token
      - DATABASE_URL=postgres://postgres:root@contracts-postgres:5432/contracts
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      network: host
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://10.0.0.3:3000
    container_name: contracts-frontend
    ports:
      - "8080:80"

  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=contracts
    container_name: contracts-postgres
