import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import Layout from "../layout";
import { Link } from "react-router";
import { ArrowRight, FileText, Users } from "lucide-react";
import { Card, CardDescription, CardHeader, CardTitle, } from "@/components/ui/card";
import ShowIf from "@/components/logic/show-if";
// Esto de usar el layout asi con react-router, está mal,
// pero lo voy a hacer así para terminar rápido
export default function Home() {
    return (_jsx(Layout, { children: _jsxs("div", { className: "container mx-auto px-4 py-12", children: [_jsxs("section", { className: "flex flex-col items-center gap-6 text-center", children: [_jsxs("h1", { className: "text-4xl font-bold tracking-tight text-balance md:text-5xl lg:text-6xl", children: ["Gestiona tus contratos de forma", " ", _jsx("span", { className: "text-primary", children: "sencilla" })] }), _jsx("p", { className: "max-w-2xl text-lg text-pretty text-muted-foreground", children: "Una plataforma completa para administrar usuarios y contratos. Organiza, busca y mant\u00E9n el control de toda tu documentaci\u00F3n en un solo lugar." }), _jsxs("div", { className: "flex flex-wrap justify-center gap-4", children: [_jsx(ShowIf, { allow: ["CONSULTOR", "OPERADOR"], children: _jsx(Button, { asChild: true, size: "lg", children: _jsxs(Link, { to: "/contracts", children: ["Ver contratos", _jsx(ArrowRight, { className: "ml-2 h-4 w-4" })] }) }) }), _jsx(Button, { asChild: true, variant: "outline", size: "lg", children: _jsx(Link, { to: "/users", children: "Ver usuarios" }) })] })] }), _jsxs("section", { className: "mt-20 grid gap-6 md:grid-cols-2", children: [_jsx(Card, { className: "transition-shadow hover:shadow-lg", children: _jsxs(CardHeader, { children: [_jsx("div", { className: "mb-2 flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10", children: _jsx(Users, { className: "h-6 w-6 text-primary" }) }), _jsx(CardTitle, { children: "Gesti\u00F3n de Usuarios" }), _jsx(CardDescription, { children: "Administra los usuarios de tu sistema. Agrega, edita y organiza la informaci\u00F3n de cada persona de manera eficiente." })] }) }), _jsx(Card, { className: "transition-shadow hover:shadow-lg", children: _jsxs(CardHeader, { children: [_jsx("div", { className: "mb-2 flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10", children: _jsx(FileText, { className: "h-6 w-6 text-primary" }) }), _jsx(CardTitle, { children: "Gesti\u00F3n de Contratos" }), _jsx(CardDescription, { children: "Crea y gestiona contratos f\u00E1cilmente. Mant\u00E9n un registro organizado de todos los documentos importantes." })] }) })] })] }) }));
}
